// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: div.proto

package divpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DivService_Compute_FullMethodName = "/calculator.div.DivService/Compute"
)

// DivServiceClient is the client API for DivService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DivServiceClient interface {
	Compute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
}

type divServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDivServiceClient(cc grpc.ClientConnInterface) DivServiceClient {
	return &divServiceClient{cc}
}

func (c *divServiceClient) Compute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, DivService_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DivServiceServer is the server API for DivService service.
// All implementations must embed UnimplementedDivServiceServer
// for forward compatibility.
type DivServiceServer interface {
	Compute(context.Context, *OperationRequest) (*OperationResponse, error)
	mustEmbedUnimplementedDivServiceServer()
}

// UnimplementedDivServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDivServiceServer struct{}

func (UnimplementedDivServiceServer) Compute(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedDivServiceServer) mustEmbedUnimplementedDivServiceServer() {}
func (UnimplementedDivServiceServer) testEmbeddedByValue()                    {}

// UnsafeDivServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DivServiceServer will
// result in compilation errors.
type UnsafeDivServiceServer interface {
	mustEmbedUnimplementedDivServiceServer()
}

func RegisterDivServiceServer(s grpc.ServiceRegistrar, srv DivServiceServer) {
	// If the following call pancis, it indicates UnimplementedDivServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DivService_ServiceDesc, srv)
}

func _DivService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DivServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DivService_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DivServiceServer).Compute(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DivService_ServiceDesc is the grpc.ServiceDesc for DivService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DivService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.div.DivService",
	HandlerType: (*DivServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _DivService_Compute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "div.proto",
}
