// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: mul.proto

package mulpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MulService_Compute_FullMethodName = "/calculator.mul.MulService/Compute"
)

// MulServiceClient is the client API for MulService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MulServiceClient interface {
	Compute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
}

type mulServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMulServiceClient(cc grpc.ClientConnInterface) MulServiceClient {
	return &mulServiceClient{cc}
}

func (c *mulServiceClient) Compute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, MulService_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MulServiceServer is the server API for MulService service.
// All implementations must embed UnimplementedMulServiceServer
// for forward compatibility.
type MulServiceServer interface {
	Compute(context.Context, *OperationRequest) (*OperationResponse, error)
	mustEmbedUnimplementedMulServiceServer()
}

// UnimplementedMulServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMulServiceServer struct{}

func (UnimplementedMulServiceServer) Compute(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedMulServiceServer) mustEmbedUnimplementedMulServiceServer() {}
func (UnimplementedMulServiceServer) testEmbeddedByValue()                    {}

// UnsafeMulServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MulServiceServer will
// result in compilation errors.
type UnsafeMulServiceServer interface {
	mustEmbedUnimplementedMulServiceServer()
}

func RegisterMulServiceServer(s grpc.ServiceRegistrar, srv MulServiceServer) {
	// If the following call pancis, it indicates UnimplementedMulServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MulService_ServiceDesc, srv)
}

func _MulService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MulServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MulService_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MulServiceServer).Compute(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MulService_ServiceDesc is the grpc.ServiceDesc for MulService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MulService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.mul.MulService",
	HandlerType: (*MulServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _MulService_Compute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mul.proto",
}
